### ISSUE TITLE
Get XHGui working or document it

### ISSUE THREAD

**Issue by roborourke** [Chassis/xhprof#11]
Currently there's a rule to auto prepend xhgui's header file but it doesn't exist in this repo. Maybe just needs adding as a submodule.

**Comment by BronsonQuick** [comment]
I've removed the references to Xhgui for now. I'm making a new extension that will get Xhgui working. I've already had to fork two repos for bug fixes but I think I'll have something for you soon!

**Comment by BronsonQuick** [comment]
@roborourke I forgot to circle back before I went home to drop a link to the finished extension for you: https://github.com/Chassis/chassis-xhgui I'll post about it internally in my Weekly Update next week.
